import http from 'node:http';
import { analyticsSummary } from './analytics.mjs';

const html = `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Useful Tech Manager</title><link rel="stylesheet" href="/dashboard.css"></head><body><main><div class="brand">تقنية تفيدك <small>Useful Tech Manager</small></div><p class="sub">لوحة معلومات خاصة للقراءة فقط.</p><div id="overview" class="grid"></div><h2>المحتوى</h2><table><thead><tr><th>الموضوع</th><th>الحالة</th><th>المراجعة</th><th>آخر تحديث</th></tr></thead><tbody id="content"></tbody></table></main><script src="/dashboard.js" defer></script></body></html>`;
const css = `body{margin:0;background:#f7f8fa;color:#102238;font:16px Inter,Arial,sans-serif}main{max-width:1050px;margin:auto;padding:38px 20px}.brand{font-weight:800;font-size:27px}.sub{color:#5b6978;margin:7px 0 30px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.card{background:#fff;border:1px solid #e4e9ef;border-radius:18px;padding:18px;box-shadow:0 8px 22px #17304c0b}.label{color:#657386;font-size:13px}.value{font-size:24px;font-weight:750;margin-top:7px}h2{font-size:19px;margin-top:32px}table{width:100%;border-collapse:collapse;background:#fff;border-radius:16px;overflow:hidden}th,td{padding:13px;text-align:right;border-bottom:1px solid #eef1f4}th{color:#657386;font-size:13px}small{color:#657386}`;
const js = `const esc=v=>String(v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));Promise.all([fetch('/api/overview'),fetch('/api/content')]).then(async r=>[await r[0].json(),await r[1].json()]).then(([o,c])=>{document.querySelector('#overview').innerHTML=[['المحتوى',o.contentCount],['قيد المراجعة',o.readyForReview],['المعتمد',o.approved],['لقطات التحليلات',o.analyticsCount]].map(x=>'<div class=card><div class=label>'+esc(x[0])+'</div><div class=value>'+esc(x[1])+'</div></div>').join('');document.querySelector('#content').innerHTML=c.items.map(x=>'<tr><td>'+esc(x.topic)+'</td><td>'+esc(x.state)+'</td><td>'+esc(x.current_revision)+'</td><td>'+esc(x.updated_at)+'</td></tr>').join('')||'<tr><td colspan=4>لا يوجد محتوى بعد</td></tr>';});`;
export function createDashboard(store, config) {
  if (config.dashboardHost !== '127.0.0.1' && config.dashboardHost !== '::1') throw new Error('Dashboard must bind loopback only');
  return http.createServer((request, response) => {
    if (request.method !== 'GET' && request.method !== 'HEAD') { response.writeHead(405, { Allow: 'GET, HEAD' }); return response.end(); }
    const url = new URL(request.url, 'http://localhost'); const headers = { 'content-security-policy': "default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'", 'x-content-type-options': 'nosniff', 'cache-control': 'no-store' };
    if (url.pathname === '/dashboard.css') { response.writeHead(200, { ...headers, 'content-type': 'text/css; charset=utf-8' }); return response.end(css); }
    if (url.pathname === '/dashboard.js') { response.writeHead(200, { ...headers, 'content-type': 'application/javascript; charset=utf-8' }); return response.end(js); }
    if (url.pathname === '/api/content') { response.writeHead(200, { ...headers, 'content-type': 'application/json' }); return response.end(JSON.stringify({ items: store.listContent() })); }
    if (url.pathname === '/api/analytics') { response.writeHead(200, { ...headers, 'content-type': 'application/json' }); return response.end(JSON.stringify(analyticsSummary(store))); }
    if (url.pathname === '/api/overview') { const rows = store.listContent(500); const analyticsCount = store.db.prepare('SELECT count(*) AS value FROM analytics_snapshots').get().value; response.writeHead(200, { ...headers, 'content-type': 'application/json' }); return response.end(JSON.stringify({ contentCount: rows.length, readyForReview: rows.filter((x) => x.state === 'READY_FOR_REVIEW').length, approved: rows.filter((x) => ['APPROVED','ARCHIVED','PUBLISHED'].includes(x.state)).length, analyticsCount })); }
    if (url.pathname === '/') { response.writeHead(200, { ...headers, 'content-type': 'text/html; charset=utf-8' }); return response.end(html); }
    response.writeHead(404, headers); response.end('Not found');
  });
}
